spring.application.name=finance-rpg

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_DB
spring.datasource.username=postgres
spring.datasource.password=1235
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Port
server.port=8080

# LINE Bot
line.bot.channel-token=Rg4l6Y9MI2NoWOrO9Bo3RdRqIRCENDkZ1xD/Jlboacq6mx8N0p6RCOxH6eTeM1NmZ/wVc1iNxwoBlqVQC6x0IEB6VtF8jgRCHeB5H2enkkJr4/4ORqqqm5hKvHZwwNmnL/m1sdfXhc5x5F9kgzxhgAdB04t89/1O/w1cDnyilFU=
line.bot.channel-secret=6372e2efd779f9aea1505d49cb3d3f89